"""Sensitive error minimization at observability trust boundaries (ADR-034).

This module is intentionally small and dependency-light.  It is not a general
secret scanner: external text is summarized by category, while trusted/mixed
text receives conservative credential redaction, one-line normalization, and
an explicit length bound before it may enter durable state or diagnostics.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from typing import Any, Iterable


class ErrorSource(str, Enum):
    """Who controls diagnostic message text at the persistence boundary."""

    TRUSTED = "trusted"
    MIXED = "mixed"
    EXTERNAL = "external"


_EXTERNAL_CATEGORIES = frozenset({
    "provider_unavailable",
    "provider_auth",
    "provider_config",
    "malformed_response",
    "model",
})

_EXTERNAL_MESSAGES = {
    "provider_unavailable": "provider unavailable",
    "provider_auth": "provider authentication failed",
    "provider_config": "provider request rejected",
    "malformed_response": "provider returned malformed response",
    "schema_validation": "provider response failed schema validation",
    "capability_validation": "provider plan failed capability validation",
    "plan_validation": "plan validation failed",
    "planning": "planning failed",
    "model": "model operation failed",
    "reflection_validation": "model reflection failed validation",
}

_CONTROL_CHARS = re.compile(r"[\r\n\t]+")
_BEARER = re.compile(r"(?i)\bBearer\s+[A-Za-z0-9._~+/=-]+")
_OPENAI_STYLE_KEY = re.compile(r"\bsk-[A-Za-z0-9_-]{8,}\b")
_SENSITIVE_ASSIGNMENT = re.compile(
    r"(?i)\b(authorization|proxy-authorization|api[ _-]?(?:key|token)|"
    r"access[ _-]?token|refresh[ _-]?token|secret[ _-]?token|"
    r"client[ _-]?secret|private[ _-]?key|token|secret|password|passwd)\b"
    r"([\"']?\s*[:=]\s*)(?:Bearer\s+)?"
    r"(?:\"[^\"]*\"|'[^']*'|[^\s,;]+)"
)
_HTTP_STATUS = re.compile(r"(?i)\bHTTP\s+([1-5][0-9]{2})\b")


def _bound(text: str, max_length: int) -> str:
    if isinstance(max_length, bool) or not isinstance(max_length, int) or max_length < 1:
        raise ValueError("max_length must be a positive integer")
    if len(text) <= max_length:
        return text
    if max_length <= 3:
        return text[:max_length]
    return text[: max_length - 3] + "..."


def sanitize_error_text(
    value: object,
    *,
    max_length: int = 300,
    secrets: Iterable[str] = (),
) -> str:
    """Return a bounded one-line diagnostic with conservative redaction.

    Exact caller-known secrets are replaced first.  A deliberately small set
    of credential conventions then covers bearer values, OpenAI-style keys,
    and common assignment/header names.  Arbitrary prose and identifiers are
    otherwise retained for trusted/mixed diagnostics.
    """
    text = str(value)
    text = _CONTROL_CHARS.sub(" ", text)
    for secret in sorted(
        {secret for secret in secrets if isinstance(secret, str) and secret},
        key=len,
        reverse=True,
    ):
        text = text.replace(secret, "<redacted>")
    text = _BEARER.sub("Bearer <redacted>", text)
    text = _SENSITIVE_ASSIGNMENT.sub(
        lambda match: f"{match.group(1)}{match.group(2)}<redacted>",
        text,
    )
    text = _OPENAI_STYLE_KEY.sub("<redacted>", text)
    return _bound(text, max_length)


@dataclass(frozen=True)
class ErrorSummary:
    """Structured, event-compatible summary of one failure."""

    message: str
    error_type: str
    category: str
    source: ErrorSource

    def to_event_detail(self) -> dict[str, Any]:
        return {
            "error": self.message,
            "error_type": self.error_type,
            "category": self.category,
            "error_source": self.source.value,
        }


def classify_error_source(error: BaseException) -> ErrorSource:
    """Classify typed provider errors as external; validator templates mixed.

    Plan/schema/capability validation messages are generated by Arion and are
    useful for fail-closed diagnosis, although their identifiers may originate
    in a model plan. They therefore use trusted-text redaction and bounds.
    Provider transport/body categories retain no source text at all.
    """
    category = getattr(error, "category", "unknown")
    return (
        ErrorSource.EXTERNAL
        if category in _EXTERNAL_CATEGORIES
        else ErrorSource.MIXED
    )


def summarize_error(
    error: BaseException,
    *,
    source: ErrorSource,
    category: str | None = None,
    max_length: int = 300,
    secrets: Iterable[str] = (),
) -> ErrorSummary:
    """Create a structured summary under an explicit trust policy.

    EXTERNAL source text is never retained.  Only a fixed category message and
    an optional numeric HTTP status extracted from the source are kept.
    TRUSTED/MIXED source text remains useful after redaction and bounding.
    """
    if not isinstance(error, BaseException):
        raise TypeError("error must be an exception")
    raw_category = category or getattr(error, "category", "unknown") or "unknown"
    safe_category = sanitize_error_text(raw_category, max_length=80)
    if source is ErrorSource.EXTERNAL:
        message = _EXTERNAL_MESSAGES.get(
            safe_category,
            "external operation failed",
        )
        status = _HTTP_STATUS.search(str(error))
        if status is not None:
            message = f"{message} (HTTP {status.group(1)})"
        message = _bound(message, max_length)
    elif source in (ErrorSource.TRUSTED, ErrorSource.MIXED):
        message = sanitize_error_text(
            error,
            max_length=max_length,
            secrets=secrets,
        )
    else:  # fail closed if a future enum/value bypasses the explicit policy
        raise ValueError(f"unsupported error source: {source!r}")
    return ErrorSummary(
        message=message,
        error_type=type(error).__name__,
        category=safe_category,
        source=source,
    )
